### ISSUE TITLE
Very minor: README.md: build-ext <-- build_ext

### ISSUE THREAD

**Issue by texadactyl** [esandford/EightBitTransit#2]
When you have a spare moment, please fix README.md.  The '-' is parallel to a '_' so it fooled me for a bit!

By the way, the project compiles well with Python 3.6.7 on Xubuntu Linux 18.04.1 LTS and Raspberry Pi Raspbian 2018-11-26.

**Comment by esandford** [comment]
Ah, thanks for catching that! Fixing now.
