### ISSUE TITLE
Not urgent but github ideally would be at a clean/zero state

### ISSUE THREAD

**Issue by texadactyl** [esandford/EightBitTransit#3]
I suggest that github contain no .c files in the EightBitTransit subfolder. Then, the downloader is for sure starting from scratch i.e. with cythonizing.

Nice to have: shell script to remove the {*.c, *.so, *.dll} files in the EightBitTransit subfolder and the entire build subtree.

**Comment by esandford** [comment]
Ah yes, good point. I'll .gitignore those, actually.
