### ISSUE TITLE
Sometimes, running out of memory (easy fto fix)

### ISSUE THREAD

**Issue by texadactyl** [esandford/EightBitTransit#4]
Repeated TransitingImage() calls can, in some circumstances, cause python/python3 to run out of memory.  

ti = TransitingImage(...)
ti.plot_grid()
etc.

I suggest that you simply warn the user to add an explicit deallocation when they are done with the transiting image object:

ti = None

That is, just handle it with documentation and example code.

By the way, I also saw other opportunities for improvement (hope I am not being a pest):
(1) cTransitingImage.pyx/plot_grid() - just before returning None, insert 1 line of code to deallocate the matplotlib structure since you have no further use of it i.e. plt.close()
(2) In the *.pyx code, there is a lot of commented out code (E.g. inversion.pyx).  The python interpreter has to scan and skip over it.  Time to remove it?
(3) inversion.pyx has  an import for matplotlib.pyplot that is unused that can be removed.

**Comment by esandford** [comment]
You're not being a pest at all, thank you for all these suggestions!

**Comment by texadactyl** [comment]
Your article is very interesting.  I do not claim to, as of yet, understand it well.  My skills are Software Engineering (since the days of punched cards and paper tape). I am learning a bit of Astrophysics through on-line classes.

**Comment by esandford** [comment]
Thanks! Glad you're enjoying it.
